Fix empty call with "pysemver" and "pysemver bump"
* Raise SystemExit when "pysemver" is called without
  arguments.
* When "pysemver bump" is called without arguments,
  print the help text for the bump subcommand and
  exit.
* Add test cases for both calls
* Update CHANGELOG

Without this patch, "pysemver bump" raises an AttributeError:

```
Traceback (most recent call last):
  File ".tox/py36/bin/pysemver", line 8, in <module>
    sys.exit(main())
  File ".tox/py36/lib/python3.6/site-packages/semver.py", line 726, in main
    result = process(args)
  File ".tox/py36/lib/python3.6/site-packages/semver.py", line 693, in process
    if args.which == "bump":
AttributeError: 'Namespace' object has no attribute 'which'
```