Use literal strings in setup.cfg
Due to https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#metadata
we cannot use the "attr:" type in the keywords author, author_email, maintainer,
description, and maintainer_email.

If we do not change it to literal strings, twine (or PyPI) complains about the metadata
with the following error:

HTTPError: 400 Client Error: 'attr: semver.__about__.__author_email__' is an invalid value for
Author-email.