Fix pydantic/semver example
The current example, when used with semver 3.0.0.dev4 and pydantic
1.10.4, produces the following error:

  pydantic.errors.ConfigError: Invalid signature for validator <bound
  method Version.parse of <class '__main__.PydanticVersion'>>: (version:
  Union[str, bytes], optional_minor_and_patch: bool = False) ->
  'Version', should be: (value, values, config, field), "values",
  "config" and "field" are all optional.

This commit fixes the example in the documentation so that it works and
does not raise an error.